const PRODUCTS = [
    {
        id: 1,
        barcode: "4791000123456",
        name: "Anchor Full Cream Milk 1L",
        category: "Dairy",
        price: 450,
        cost: 380,
        stock: 42,
        emoji: "🥛",
        unit: "bottle",
        taxRate: 0
    },
    {
        id: 2,
        barcode: "4791000123457",
        name: "Munchee Chocolate Puff",
        category: "Bakery",
        price: 180,
        cost: 135,
        stock: 85,
        emoji: "🍪",
        unit: "pack",
        taxRate: 0
    },
    {
        id: 3,
        barcode: "4791000123458",
        name: "Keells Basmati Rice 5KG",
        category: "Groceries",
        price: 2850,
        cost: 2450,
        stock: 18,
        emoji: "🍚",
        unit: "bag",
        taxRate: 0
    },
    {
        id: 4,
        barcode: "4791000123459",
        name: "Coca-Cola 1.5L",
        category: "Beverages",
        price: 420,
        cost: 340,
        stock: 64,
        emoji: "🥤",
        unit: "bottle",
        taxRate: 0
    },
    {
        id: 5,
        barcode: "4791000123460",
        name: "Prima Bread 450G",
        category: "Bakery",
        price: 220,
        cost: 175,
        stock: 27,
        emoji: "🍞",
        unit: "loaf",
        taxRate: 0
    },
    {
        id: 6,
        barcode: "4791000123461",
        name: "Eggs 10 Pack",
        category: "Dairy",
        price: 650,
        cost: 575,
        stock: 11,
        emoji: "🥚",
        unit: "pack",
        taxRate: 0
    },
    {
        id: 7,
        barcode: "4791000123462",
        name: "Shan Chicken Curry Powder",
        category: "Groceries",
        price: 310,
        cost: 245,
        stock: 31,
        emoji: "🌶️",
        unit: "pack",
        taxRate: 0
    },
    {
        id: 8,
        barcode: "4791000123463",
        name: "Nescafe Classic 100G",
        category: "Beverages",
        price: 1250,
        cost: 1040,
        stock: 7,
        emoji: "☕",
        unit: "jar",
        taxRate: 0
    },
    {
        id: 9,
        barcode: "4791000123464",
        name: "Fresh Bananas 1KG",
        category: "Fresh",
        price: 360,
        cost: 285,
        stock: 23,
        emoji: "🍌",
        unit: "kg",
        taxRate: 0
    },
    {
        id: 10,
        barcode: "4791000123465",
        name: "Sunlight Dishwash 500ML",
        category: "Household",
        price: 520,
        cost: 420,
        stock: 16,
        emoji: "🧴",
        unit: "bottle",
        taxRate: 0
    },
    {
        id: 11,
        barcode: "4791000123466",
        name: "Munchee Cream Cracker",
        category: "Bakery",
        price: 260,
        cost: 205,
        stock: 54,
        emoji: "🍘",
        unit: "pack",
        taxRate: 0
    },
    {
        id: 12,
        barcode: "4791000123467",
        name: "CIC Sugar 1KG",
        category: "Groceries",
        price: 290,
        cost: 245,
        stock: 38,
        emoji: "🧂",
        unit: "pack",
        taxRate: 0
    }
];